# Generated by Django 5.1.6 on 2025-03-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_form_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='submitted_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
