# Generated by Django 5.1.6 on 2025-03-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_formresponse_submitted_by_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponsefield',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='form_uploads/'),
        ),
    ]
